"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type CheckIn = { id: string; scannedAt: string; barcode: string; studentName: string; nationalId: string };
type Session = { id: string; name: string; examRound: string; academicYear: number; startedAt: string; checkedInCount: number; recentCheckIns: CheckIn[]; examLocation: { name: string; province: string | null } | null };
type Bootstrap = { sessions: Session[]; locations: Array<{ id: string; code: string; name: string; province: string | null }>; isCheckInOpen: boolean };
const card = "rounded-xl border border-stroke bg-white p-5 shadow-1 dark:border-stroke-dark dark:bg-gray-dark";

export default function GatpatCheckinPage() {
  const [state, setState] = useState<Bootstrap | null>(null); const [round, setRound] = useState("MORNING"); const [locationId, setLocationId] = useState(""); const [barcode, setBarcode] = useState(""); const [sessionId, setSessionId] = useState(""); const [message, setMessage] = useState(""); const [result, setResult] = useState<{ name: string; location: string; barcode: string; nationalId: string; checkedAt: string } | null>(null); const [busy, setBusy] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (background = false) => {
    if (background) setRefreshing(true);
    try { const response = await fetch("/api/gatpat/admin/checkin/bootstrap", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "โหลด session ไม่สำเร็จ"); setState(body); setSessionId((current) => body.sessions.some((x: Session) => x.id === current) ? current : body.sessions[0]?.id ?? ""); setLocationId((current) => current || body.locations[0]?.id || ""); }
    catch (error) { setMessage(error instanceof Error ? error.message : "โหลด session ไม่สำเร็จ"); }
    finally { if (background) setRefreshing(false); }
  }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(true); }, 10_000); return () => window.clearInterval(timer); }, [load]);
  const selectedSession = useMemo(() => state?.sessions.find((session) => session.id === sessionId) ?? null, [state, sessionId]);

  async function startSession() {
    if (selectedSession && !window.confirm("จะปิด session เดิมของบัญชีนี้และเปิด session ใหม่ ต้องการดำเนินการหรือไม่?")) return;
    setBusy(true); setMessage(""); setResult(null);
    try { const response = await fetch("/api/gatpat/admin/checkin/sessions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ examRound: round, examLocationId: locationId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "เปิด session ไม่สำเร็จ"); setSessionId(body.id); setMessage("เปิด session ใหม่แล้ว · session ก่อนหน้าถูกปิดและประวัติเดิมยังคงอยู่"); await load(); setSessionId(body.id); }
    catch (error) { setMessage(error instanceof Error ? error.message : "เกิดข้อผิดพลาด"); } finally { setBusy(false); }
  }
  async function scan(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); setResult(null);
    try { const response = await fetch("/api/gatpat/admin/checkin/scan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ barcode, sessionId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || (body.duplicate ? "รายการนี้เช็คอินแล้ว" : "เช็คอินไม่สำเร็จ")); setResult({ name: body.studentName, location: body.location, barcode, nationalId: body.nationalId ?? "", checkedAt: new Date(body.checkIn?.scannedAt ?? Date.now()).toLocaleTimeString("th-TH", { timeZone: "Asia/Bangkok", hour: "2-digit", minute: "2-digit", second: "2-digit" }) }); setMessage("เช็คอินสำเร็จ"); setBarcode(""); await load(true); }
    catch (error) { setMessage(error instanceof Error ? error.message : "เกิดข้อผิดพลาด"); } finally { setBusy(false); }
  }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="mt-1 text-2xl font-bold text-dark dark:text-white">Check-in หน้างาน</h1><p className="mt-1 text-sm text-dark-6">สแกนบาร์โค้ด 8 หลัก · อัปเดตรายการล่าสุดทุก 10 วินาที{refreshing ? " · กำลังอัปเดต" : ""}</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${state?.isCheckInOpen ? "bg-green/10 text-green" : "bg-red/10 text-red"}`}>{state?.isCheckInOpen ? "ระบบเปิด" : "ระบบปิด"}</span></div>
    {message && <p role="status" className={`rounded-lg border p-3 text-sm ${result ? "border-green/20 bg-green/5 text-green" : "border-stroke bg-white text-dark-6 dark:border-stroke-dark dark:bg-gray-dark"}`}>{message}</p>}
    {result && <section className="rounded-xl border border-green/30 bg-green/5 p-5"><p className="text-sm font-semibold text-green">ยืนยันการเข้าสอบสำเร็จ</p><div className="mt-3 grid gap-3 sm:grid-cols-4"><div><p className="text-xs text-dark-6">ชื่อ</p><p className="font-semibold text-dark dark:text-white">{result.name}</p></div><div><p className="text-xs text-dark-6">เลขบัตร</p><p className="font-mono font-semibold text-dark dark:text-white">{result.nationalId || "—"}</p></div><div><p className="text-xs text-dark-6">บาร์โค้ด</p><p className="font-mono font-semibold text-dark dark:text-white">{result.barcode}</p></div><div><p className="text-xs text-dark-6">เวลา</p><p className="font-semibold text-dark dark:text-white">{result.checkedAt}</p></div></div><p className="mt-2 text-sm text-dark-6">{result.location}</p></section>}
    {!state?.isCheckInOpen && <p className="rounded-lg border border-amber/30 bg-amber/10 p-4 text-sm text-amber-800">ผู้ดูแลระบบปิด Check-in ไว้ จึงไม่สามารถบันทึกการสแกนได้</p>}
    <div className="grid gap-5 xl:grid-cols-[minmax(300px,0.9fr)_minmax(0,1.4fr)]">
      <section className={card}><div className="flex items-center justify-between"><div><h2 className="font-semibold text-dark dark:text-white">เปิดรอบเช็คอิน</h2><p className="mt-1 text-xs text-dark-6">เริ่ม session ใหม่จะปิด session ที่เปิดก่อนหน้าของบัญชีนี้</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">ปี {((new Date().getFullYear() + 543)).toLocaleString("th-TH")}</span></div><div className="mt-4 grid gap-3"><label className="grid gap-1 text-xs text-dark-6">รอบสอบ<select className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2" value={round} onChange={(event) => setRound(event.target.value)}><option value="MORNING">เช้า</option><option value="AFTERNOON">บ่าย</option></select></label><label className="grid gap-1 text-xs text-dark-6">สนามสอบ<select className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2" value={locationId} onChange={(event) => setLocationId(event.target.value)}>{state?.locations.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} {item.province}</option>)}</select></label><button disabled={busy || !locationId} onClick={() => void startSession()} className="rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{selectedSession ? "บันทึกยอดจุดนี้แล้วเริ่มนับใหม่" : "เปิด session เช็คอิน"}</button></div><h3 className="mt-6 text-sm font-semibold text-dark dark:text-white">เลือก session ที่เปิดอยู่</h3><div className="mt-2 space-y-2">{state?.sessions.map((session) => <button key={session.id} onClick={() => setSessionId(session.id)} className={`w-full rounded-lg border p-3 text-left ${session.id === sessionId ? "border-primary bg-primary/5" : "border-stroke dark:border-stroke-dark"}`}><div className="flex justify-between gap-2"><span className="text-sm font-semibold text-dark dark:text-white">{session.name}</span><span className="text-sm font-bold text-primary">{session.checkedInCount.toLocaleString("th-TH")} คน</span></div><p className="mt-1 text-xs text-dark-6">{session.examLocation?.name ?? "ไม่ระบุสนาม"} · {session.examRound}</p></button>)}{!state?.sessions.length && <p className="rounded-lg border border-dashed border-stroke p-4 text-center text-sm text-dark-6">ยังไม่มี session ที่เปิดอยู่</p>}</div></section>
      <section className={card}><div className="flex items-center justify-between"><div><h2 className="font-semibold text-dark dark:text-white">สแกนบาร์โค้ด</h2><p className="mt-1 text-xs text-dark-6">{selectedSession ? `${selectedSession.name} · ${selectedSession.examLocation?.name ?? "ไม่ระบุสนาม"}` : "เลือก session ก่อนเริ่มสแกน"}</p></div><span className="rounded-full bg-gray-2 px-3 py-1 text-xs font-medium text-dark-6 dark:bg-dark-2">{selectedSession?.checkedInCount ?? 0} เช็คอิน</span></div><form onSubmit={scan} className="mt-5 space-y-3"><input className="w-full rounded-xl border border-stroke bg-gray-2 px-4 py-5 text-center font-mono text-3xl tracking-[0.3em] text-dark placeholder:text-gray-5 dark:border-stroke-dark dark:bg-dark-2 dark:text-white" value={barcode} onChange={(event) => setBarcode(event.target.value.replace(/\D/g, "").slice(0, 8))} inputMode="numeric" autoFocus maxLength={8} placeholder="00000000" required/><p className="text-center text-xs text-dark-6">สแกนเครื่องอ่านหรือกรอกรหัส 8 หลัก</p><button disabled={busy || !sessionId || !state?.isCheckInOpen || barcode.length !== 8} className="w-full rounded-lg bg-primary px-4 py-3 font-semibold text-white disabled:opacity-40">{busy ? "กำลังตรวจสอบ…" : "ยืนยัน Check-in"}</button></form><div className="mt-6"><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-semibold text-dark dark:text-white">รายการสแกนล่าสุด</h3><span className="text-xs text-dark-6">สูงสุด 10 รายการ</span></div><div className="overflow-x-auto"><table className="w-full min-w-[450px] text-left text-xs"><thead className="bg-gray-2 text-dark-6 dark:bg-dark-2"><tr><th className="p-2">เวลา</th><th className="p-2">นักเรียน</th><th className="p-2">บาร์โค้ด</th></tr></thead><tbody>{selectedSession?.recentCheckIns.length ? selectedSession.recentCheckIns.map((item) => <tr key={item.id} className="border-t border-stroke dark:border-stroke-dark"><td className="p-2">{new Date(item.scannedAt).toLocaleTimeString("th-TH", { timeZone: "Asia/Bangkok" })}</td><td className="p-2">{item.studentName}<p className="text-dark-6">{item.nationalId}</p></td><td className="p-2 font-mono">{item.barcode}</td></tr>) : <tr><td colSpan={3} className="p-5 text-center text-dark-6">ยังไม่มีประวัติใน session นี้</td></tr>}</tbody></table></div></div></section>
    </div>
  </div>;
}
