"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import ExcelJS from "exceljs";

type RequestRow = { id: string; enrollmentId: string; status: "PENDING" | "IN_PROGRESS" | "COMPLETED"; reason: string; fullName: string; address: string; phone: string; submittedAt: string; processedAt: string | null; academicYear: number; examRound: string; barcode: string; sourceType: string; nationalId: string; studentName: string; location: string; province: string };
const card = "rounded-xl border border-stroke bg-white shadow-1 dark:border-stroke-dark dark:bg-gray-dark";
const labels = { PENDING: "รอดำเนินการ", IN_PROGRESS: "กำลังดำเนินการ", COMPLETED: "สำเร็จ" };
const categories = ["onsite-review", "simulated-exam", "other"] as const;

function categoryOf(row: RequestRow) { return row.sourceType === "ONSITE_EXCEL" ? "onsite-review" : row.sourceType === "SIMULATED_EXCEL" ? "simulated-exam" : "other"; }

export default function GatpatForfeitRequestsPage() {
  const [rows, setRows] = useState<RequestRow[]>([]); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [categoryFilter, setCategoryFilter] = useState("");
  const [notice, setNotice] = useState(""); const [busyId, setBusyId] = useState(""); const [selected, setSelected] = useState<RequestRow | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/gatpat/admin/forfeit-requests", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "โหลดคำขอไม่สำเร็จ"); setRows(body); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "โหลดคำขอไม่สำเร็จ"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => {
    const q = search.trim().toLocaleLowerCase(); const target = [row.studentName, row.nationalId, row.barcode, row.fullName, row.phone, row.reason, row.location].join(" ").toLocaleLowerCase();
    return (!q || target.includes(q)) && (!statusFilter || row.status === statusFilter) && (!categoryFilter || categoryOf(row) === categoryFilter);
  }), [rows, search, statusFilter, categoryFilter]);

  async function setStatus(row: RequestRow, status: RequestRow["status"]) {
    if (status === "COMPLETED" && row.status !== "COMPLETED" && !window.confirm("ยืนยันปิดคำขอนี้ว่าสำเร็จหรือไม่? ใบสมัครที่เชื่อมอยู่จะถูกยกเลิก")) return;
    setBusyId(row.id); setNotice("");
    try { const response = await fetch(`/api/gatpat/admin/forfeit-requests/${encodeURIComponent(row.id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "อัปเดตไม่สำเร็จ"); setNotice("อัปเดตสถานะแล้ว"); await load(); setSelected((current) => current?.id === row.id ? { ...current, status, processedAt: status === "COMPLETED" ? new Date().toISOString() : current.processedAt } : current); }
    catch (error) { setNotice(error instanceof Error ? error.message : "อัปเดตไม่สำเร็จ"); } finally { setBusyId(""); }
  }

  async function exportExcel() {
    const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("คำขอสละสิทธิ์");
    sheet.columns = [{ header: "ชื่อผู้สมัคร", key: "name", width: 28 }, { header: "เลขประจำตัว", key: "id", width: 18 }, { header: "บาร์โค้ด", key: "barcode", width: 14 }, { header: "หมวดหมู่", key: "category", width: 20 }, { header: "กิจกรรม", key: "event", width: 34 }, { header: "ปีการศึกษา", key: "year", width: 14 }, { header: "รอบสอบ", key: "round", width: 16 }, { header: "เหตุผล", key: "reason", width: 45 }, { header: "ผู้ติดต่อ", key: "contact", width: 24 }, { header: "โทรศัพท์", key: "phone", width: 18 }, { header: "สนามสอบ", key: "location", width: 30 }, { header: "วันที่ยื่น", key: "submitted", width: 24 }, { header: "สถานะ", key: "status", width: 22 }];
    for (const row of filtered) sheet.addRow({ name: row.studentName, id: row.nationalId, barcode: row.barcode, category: categoryOf(row), event: categoryOf(row) === "onsite-review" ? "กิจกรรมติวเก็งข้อสอบ" : "กิจกรรมสอบจำลองเสมือนจริง", year: row.academicYear, round: row.examRound, reason: row.reason, contact: row.fullName, phone: row.phone, location: [row.location, row.province].filter(Boolean).join(" · "), submitted: new Date(row.submittedAt).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" }), status: labels[row.status] });
    sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E1B4B" } };
    const buffer = await workbook.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const a = document.createElement("a"); a.href = url; a.download = `web-a-forfeit-${new Date().toISOString().slice(0, 10)}.xlsx`; a.click(); URL.revokeObjectURL(url);
  }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="mt-1 text-2xl font-bold text-dark dark:text-white">คำขอสละสิทธิ์</h1><p className="mt-1 text-sm text-dark-6">ตรวจสอบคำขอและเปลี่ยนสถานะรายใบสมัคร</p></div><button onClick={() => void exportExcel()} disabled={!filtered.length} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">ส่งออก Excel ({filtered.length})</button></div>
    {notice && <p role="status" className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm text-dark dark:text-white">{notice}</p>}
    <section className={`${card} grid gap-3 p-4 md:grid-cols-[minmax(220px,1fr)_200px_200px]`}><input className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2 dark:text-white" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ค้นหาชื่อ เลขประจำตัว บาร์โค้ด หรือเหตุผล"/><select className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2 dark:text-white" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">ทุกสถานะ</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2 dark:text-white" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="">ทุกหมวดหมู่</option>{categories.map((value) => <option key={value} value={value}>{value === "onsite-review" ? "Onsite Review" : value === "simulated-exam" ? "สอบจำลอง" : "อื่น ๆ"}</option>)}</select></section>
    <section className={`${card} overflow-hidden`}><div className="flex justify-between border-b border-stroke px-4 py-3 dark:border-stroke-dark"><h2 className="font-semibold text-dark dark:text-white">รายการคำขอ</h2><span className="text-sm text-dark-6">{filtered.length} รายการ</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-gray-2 text-dark-6 dark:bg-dark-2"><tr>{["ชื่อ / เลขประจำตัว", "หมวดหมู่", "ใบสมัคร", "เหตุผล / ติดต่อ", "วันที่ส่ง", "สถานะ", "รายละเอียด", "เปลี่ยนสถานะ"].map((x) => <th key={x} className="px-3 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>
      {loading ? <tr><td colSpan={8} className="p-10 text-center text-dark-6">กำลังโหลดรายการ…</td></tr> : filtered.length ? filtered.map((row) => <tr key={row.id} className="border-t border-stroke align-top dark:border-stroke-dark"><td className="px-3 py-3"><p className="font-semibold text-dark dark:text-white">{row.studentName}</p><p className="mt-1 font-mono text-xs text-dark-6">{row.nationalId} · {row.barcode}</p></td><td className="px-3 py-3 text-xs">{categoryOf(row)}</td><td className="px-3 py-3">{row.academicYear.toLocaleString("th-TH")} · {row.examRound}<p className="mt-1 text-xs text-dark-6">{row.location || "ไม่ระบุสนาม"}{row.province ? ` · ${row.province}` : ""}</p></td><td className="max-w-[260px] px-3 py-3"><p className="line-clamp-2">{row.reason}</p><p className="mt-1 text-xs text-dark-6">{row.fullName} · {row.phone}</p></td><td className="px-3 py-3 text-xs">{new Date(row.submittedAt).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" })}</td><td className="px-3 py-3"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{labels[row.status]}</span></td><td className="px-3 py-3"><button onClick={() => setSelected(row)} className="rounded-lg border border-stroke px-3 py-2 text-xs font-semibold text-primary">ดูรายละเอียด</button></td><td className="px-3 py-3"><select aria-label="เปลี่ยนสถานะ" disabled={busyId === row.id} value={row.status} onChange={(event) => void setStatus(row, event.target.value as RequestRow["status"])} className="rounded-lg border border-stroke px-2 py-2 text-xs dark:border-stroke-dark dark:bg-dark-2">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td></tr>) : <tr><td colSpan={8} className="p-10 text-center text-dark-6">ไม่พบคำขอตามเงื่อนไข</td></tr>}
    </tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={() => setSelected(null)}><section role="dialog" aria-modal="true" className={`${card} max-h-[90vh] w-full max-w-3xl overflow-y-auto p-6`} onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-primary">รายละเอียดคำขอสละสิทธิ์</p><h2 className="mt-1 text-xl font-bold text-dark dark:text-white">{selected.studentName} · {selected.nationalId}</h2></div><button onClick={() => setSelected(null)} className="rounded-lg border border-stroke px-3 py-2 text-sm">ปิด</button></div><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[["ผู้ยื่นคำขอ", selected.fullName], ["สถานะ", labels[selected.status]], ["หมวดหมู่", categoryOf(selected)], ["บาร์โค้ด", selected.barcode], ["ปี / รอบสอบ", `${selected.academicYear.toLocaleString("th-TH")} · ${selected.examRound}`], ["สนามสอบ", [selected.location, selected.province].filter(Boolean).join(" · ")], ["ส่งคำขอเมื่อ", new Date(selected.submittedAt).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" })], ["อัปเดตล่าสุด", selected.processedAt ? new Date(selected.processedAt).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" }) : "—"], ["เบอร์โทรศัพท์", selected.phone]].map(([label, value]) => <div key={label} className="rounded-lg bg-gray-2 p-3 dark:bg-dark-2"><dt className="text-xs text-dark-6">{label}</dt><dd className="mt-1 text-sm font-medium text-dark dark:text-white">{value || "—"}</dd></div>)}</dl><div className="mt-3 rounded-lg bg-gray-2 p-3 dark:bg-dark-2"><dt className="text-xs text-dark-6">เหตุผล</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-dark dark:text-white">{selected.reason}</dd></div><div className="mt-3 rounded-lg bg-gray-2 p-3 dark:bg-dark-2"><dt className="text-xs text-dark-6">ที่อยู่ติดต่อ</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-dark dark:text-white">{selected.address || "—"}</dd></div><div className="mt-5 flex flex-wrap gap-3"><Link className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white" href={`/gatpat/admin/students?q=${encodeURIComponent(selected.nationalId)}`}>ไปหน้าจัดการนักเรียน</Link><Link className="rounded-lg border border-stroke px-4 py-2 text-sm font-semibold text-primary" href={`/gatpat/admin/enrollments?q=${encodeURIComponent(selected.barcode)}`}>เปิดใบสมัครที่เกี่ยวข้อง</Link></div></section></div>}
  </div>;
}
