const card = "rounded-xl border border-stroke bg-white p-5 shadow-1 dark:border-stroke-dark dark:bg-gray-dark";
const guides = [
  { number: "01", title: "Dashboard", summary: "ติดตามภาพรวมของปีการศึกษาที่เลือก", steps: ["เลือกช่วงวันที่เพื่อกรองข้อมูลเช็คอิน", "ตรวจใบสมัครและจำนวนผู้ที่เช็คอินหรือยังไม่เช็คอิน", "ดูค่าเฉลี่ย TGAT, คำขอสละสิทธิ์ที่รอตรวจ และสนามที่มีรายการสูง", "ตรวจ active sessions และสถิติรายชั่วโมง"], note: "Dashboard อัปเดตอัตโนมัติทุก 30 วินาทีขณะเปิดหน้านี้" },
  { number: "02", title: "นำเข้าข้อมูล Excel", summary: "นำเข้าข้อมูลสนามสอบ ผู้สมัคร Onsite และสอบจำลอง", steps: ["กำหนดปี พ.ศ., รอบ Onsite, รอบสอบจำลอง และวันที่สอบ", "เลือกไฟล์ที่ต้องการนำเข้า (แยกนำเข้าได้)", "กดตรวจสอบ Preview และอ่านจำนวนเพิ่ม/เปลี่ยน/ผิดพลาดก่อน", "กดยืนยันนำเข้าเมื่อข้อมูลถูกต้อง แล้วตรวจผลและประวัติ", "เปิดรายการเปลี่ยนแปลงหรือ rollback จากประวัติเมื่อต้องแก้การนำเข้าที่ผิด"], note: "Preview มีวันหมดอายุ และ rollback จะปฏิเสธหากมีการแก้ข้อมูลภายหลังเพื่อป้องกันข้อมูลทับกัน" },
  { number: "03", title: "จัดการนักเรียน", summary: "ค้นและตรวจรายการสมัคร พร้อมตรวจแหล่งข้อมูลและสนามสอบ", steps: ["ค้นด้วยเลขประจำตัว ชื่อ โรงเรียน อีเมล หรือโทรศัพท์", "กรองด้วยแหล่งข้อมูล ปี พ.ศ. และรายการที่รอจับคู่สนาม", "เปลี่ยนจำนวนแถวต่อหน้าและใช้ปุ่มก่อนหน้า/ถัดไป", "เปิดชื่อนักเรียนเพื่อดูข้อมูลติดต่อและใบสมัครทั้งหมด", "ใช้ซ่อนข้อมูลเฉพาะเมื่อได้รับสิทธิ์ Admin/Superadmin"], note: "ซ่อนข้อมูลเป็น soft-delete โดยเก็บประวัติเดิมไว้" },
  { number: "04", title: "Check-in หน้างาน", summary: "เปิด session ประจำจุดสอบและบันทึกการเข้าสอบจากบาร์โค้ด", steps: ["เลือกช่วงสอบและสนาม แล้วเปิด session", "เลือก session ที่ต้องการใช้งาน", "สแกนหรือกรอกบาร์โค้ด 8 หลักแล้วกดยืนยัน", "ตรวจชื่อ เลขประจำตัว สนาม และเวลาที่แสดงหลังบันทึก", "ทวนยอด session และรายการสแกนล่าสุด; ข้อมูลใหม่จะโหลดทุก 10 วินาที"], note: "การเริ่ม session ใหม่ปิด session เดิมของบัญชีนี้ แต่ไม่ลบประวัติการเช็คอิน" },
  { number: "05", title: "คำขอสละสิทธิ์", summary: "ติดตามคำขอแยกตามใบสมัครและบันทึกสถานะงาน", steps: ["ค้นด้วยชื่อ เลขประจำตัว บาร์โค้ด เหตุผล หรือสนามสอบ", "เลือกตัวกรองสถานะและหมวดหมู่", "เปิดรายละเอียดเพื่อดูผู้ติดต่อ ที่อยู่ เหตุผล และข้อมูลใบสมัคร", "เปลี่ยนสถานะเป็นกำลังดำเนินการหรือสำเร็จ", "ก่อนเปลี่ยนเป็นสำเร็จ ให้ตรวจว่าใบสมัครที่เชื่อมอยู่ต้องถูกยกเลิก", "ส่งออก Excel ตามรายการที่กรองอยู่"], note: "ขอบเขตคำขอคือใบสมัคร; การปิดงานเป็นสำเร็จจะยกเลิกใบสมัครที่เชื่อมอยู่" },
  { number: "06", title: "ตั้งค่าระบบ", summary: "ควบคุม portal/Check-in และปรับ banner กับช่องทางติดต่อ", steps: ["เปิดหรือปิด portal และ Check-in", "ตั้งเวลาเปิด/ปิด portal ตาม Asia/Bangkok หรือปล่อยว่างหากไม่กำหนดเวลา", "แก้ประกาศและลิงก์ Google Drive, Facebook, LINE OA", "อัปโหลดแบนเนอร์หน้าค้นหาและหน้ารายละเอียดแยกกัน", "บันทึก แล้วตรวจหน้าผู้สมัครว่าค่าใหม่แสดงถูกต้อง"], note: "แก้เวลาตาราง portal ได้เฉพาะ SUPERADMIN; รูปต้องเป็น JPEG, PNG หรือ WEBP และไม่เกิน 5 MB" },
  { number: "07", title: "ผู้ใช้งานและสิทธิ์ Web A", summary: "กำหนดบัญชีและ membership ภายใน Web A", steps: ["สร้างบัญชีเจ้าหน้าที่ด้วยอีเมล ชื่อ และรหัสผ่าน", "เลือกบทบาทให้เหมาะกับงาน", "ปิดหรือเปิด membership ของ Web A เมื่อเปลี่ยนหน้าที่", "ทดสอบว่าแต่ละบัญชีเห็นเฉพาะเมนูและ API ที่อนุญาต"], note: "สิทธิ์ Web A ผูกกับ site membership และแยกจากเว็บอื่น" },
];

export default function GatpatAdminManualPage() {
  return <div className="space-y-6">
    <header className={`${card} relative overflow-hidden`}><div className="absolute -right-12 -top-14 size-48 rounded-full bg-primary/5"/><h1 className="mt-2 text-2xl font-bold text-dark dark:text-white">คู่มือการใช้งานหลังบ้าน</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-dark-6">ลำดับการทำงานสำหรับเตรียมข้อมูล ตั้งค่าระบบ และปฏิบัติงานวันสอบ อ้างอิงการทำงานใน Web A</p></header>
    <section className={`${card} border-primary/20 bg-primary/5`}><h2 className="font-semibold text-dark dark:text-white">ลำดับงานแนะนำ</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{["นำเข้าข้อมูลและตรวจ Preview", "ตรวจนักเรียนกับสถานะสนาม", "ตั้งเวลา/ประกาศ/แบนเนอร์", "เปิด Check-in session ก่อนเริ่มงาน"].map((label, index) => <div key={label} className="flex items-center gap-3 rounded-lg border border-white/80 bg-white p-3 dark:border-stroke-dark dark:bg-gray-dark"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-primary text-sm font-bold text-white">{index + 1}</span><span className="text-sm font-medium text-dark dark:text-white">{label}</span></div>)}</div><p className="mt-4 text-xs text-dark-6">ติดตามคำขอสละสิทธิ์และบัญชีผู้ใช้ตามสิทธิ์ที่ได้รับ</p></section>
    <section className="grid gap-4 xl:grid-cols-2">{guides.map((guide) => <article key={guide.number} className={`${card} overflow-hidden p-0`}><div className="flex gap-4 border-b border-stroke bg-gray-2/60 p-5 dark:border-stroke-dark dark:bg-dark-2"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-sm font-bold text-white">{guide.number}</span><div><h2 className="text-lg font-semibold text-dark dark:text-white">{guide.title}</h2><p className="mt-1 text-sm text-dark-6">{guide.summary}</p></div></div><div className="p-5"><ol className="space-y-3">{guide.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-dark-6"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{index + 1}</span><span>{step}</span></li>)}</ol><p className="mt-4 rounded-lg border border-amber/20 bg-amber/5 p-3 text-xs leading-5 text-dark-6"><strong className="text-dark dark:text-white">ข้อควรทราบ: </strong>{guide.note}</p></div></article>)}</section>
  </div>;
}
