"use client";

import { useCallback, useEffect, useState } from "react";

type Enrollment = { id: string; academicYear: number; examRound: string; status: "DRAFT" | "REGISTERED" | "PAID" | "CANCELLED"; barcode: string; eventName: string; nationalId: string; studentName: string; location: string; province: string; updatedAt: string };
type Result = { items: Enrollment[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const card = "rounded-xl border border-stroke bg-white shadow-1 dark:border-stroke-dark dark:bg-gray-dark";
const statuses: Enrollment["status"][] = ["DRAFT", "REGISTERED", "PAID", "CANCELLED"];

export default function GatpatEnrollmentsPage() {
  const [query, setQuery] = useState(""); const [search, setSearch] = useState(""); const [year, setYear] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const [busyId, setBusyId] = useState("");
  useEffect(() => { const initial = new URLSearchParams(window.location.search).get("q"); if (initial) { setQuery(initial); setSearch(initial); } }, []);
  const load = useCallback(async () => {
    setLoading(true);
    try { const params = new URLSearchParams({ q: search, page: String(page), pageSize: "25" }); if (year) params.set("academicYear", year); if (status) params.set("status", status); const response = await fetch(`/api/gatpat/admin/enrollments?${params}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "โหลดใบสมัครไม่สำเร็จ"); setResult(body); setNotice(""); }
    catch (error) { setNotice(error instanceof Error ? error.message : "โหลดใบสมัครไม่สำเร็จ"); }
    finally { setLoading(false); }
  }, [search, year, status, page]);
  useEffect(() => { void load(); }, [load]);
  async function update(row: Enrollment, next: Enrollment["status"]) {
    if (next === "CANCELLED" && !window.confirm(`ยืนยันยกเลิกใบสมัครของ ${row.studentName} (${row.barcode}) หรือไม่?`)) return;
    setBusyId(row.id); setNotice("");
    try { const response = await fetch(`/api/gatpat/admin/enrollments/${encodeURIComponent(row.id)}/status`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: next }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "เปลี่ยนสถานะไม่สำเร็จ"); await load(); setNotice("อัปเดตสถานะใบสมัครแล้ว"); }
    catch (error) { setNotice(error instanceof Error ? error.message : "เปลี่ยนสถานะไม่สำเร็จ"); }
    finally { setBusyId(""); }
  }

  return <div className="space-y-5"><div><p className="text-sm font-medium text-primary">ระบบสมัครสอบ · เว็บ A</p><h1 className="mt-1 text-2xl font-bold text-dark dark:text-white">ใบสมัครและสถานะ</h1><p className="mt-1 text-sm text-dark-6">ตรวจใบสมัครทั้งหมดและจัดการสถานะตามสิทธิ์ของเจ้าหน้าที่</p></div>
    {notice && <p role="status" className="rounded-lg border border-stroke bg-white p-3 text-sm text-dark-6 dark:border-stroke-dark dark:bg-gray-dark">{notice}</p>}
    <form onSubmit={(event) => { event.preventDefault(); setPage(1); setSearch(query); }} className={`${card} grid gap-3 p-4 md:grid-cols-[minmax(240px,1fr)_150px_190px_auto]`}><input className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาชื่อ เลขประจำตัว หรือบาร์โค้ด"/><input className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2" inputMode="numeric" value={year} onChange={(event) => { setYear(event.target.value.replace(/\D/g, "").slice(0, 4)); setPage(1); }} placeholder="ปี พ.ศ."/><select className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-stroke-dark dark:bg-dark-2" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">ทุกสถานะ</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">ค้นหา</button></form>
    <section className={`${card} overflow-hidden`}><div className="flex items-center justify-between border-b border-stroke px-4 py-3 dark:border-stroke-dark"><h2 className="font-semibold text-dark dark:text-white">รายการใบสมัคร</h2><span className="text-sm text-dark-6">{result?.meta.total.toLocaleString("th-TH") ?? 0} รายการ · หน้า {result?.meta.page ?? page}/{result?.meta.totalPages ?? 1}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-gray-2 text-dark-6 dark:bg-dark-2"><tr>{["ผู้สมัคร", "กิจกรรม / ปี / รอบ", "สนามสอบ", "บาร์โค้ด", "สถานะ", "อัปเดตล่าสุด"].map((item) => <th key={item} className="px-4 py-3 font-semibold">{item}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-8 text-center text-dark-6">กำลังโหลด…</td></tr> : result?.items.length ? result.items.map((row) => <tr key={row.id} className="border-t border-stroke dark:border-stroke-dark"><td className="px-4 py-3"><p className="font-semibold text-dark dark:text-white">{row.studentName}</p><p className="mt-1 font-mono text-xs text-dark-6">{row.nationalId}</p></td><td className="px-4 py-3">{row.eventName}<p className="mt-1 text-xs text-dark-6">พ.ศ. {row.academicYear.toLocaleString("th-TH")} · {row.examRound}</p></td><td className="px-4 py-3">{row.location || "—"}<p className="mt-1 text-xs text-dark-6">{row.province || ""}</p></td><td className="px-4 py-3 font-mono">{row.barcode}</td><td className="px-4 py-3"><select aria-label={`สถานะ ${row.barcode}`} disabled={busyId === row.id} value={row.status} onChange={(event) => void update(row, event.target.value as Enrollment["status"])} className="rounded-lg border border-stroke px-2 py-2 text-xs dark:border-stroke-dark dark:bg-dark-2">{statuses.map((value) => <option key={value}>{value}</option>)}</select></td><td className="px-4 py-3 text-xs text-dark-6">{new Date(row.updatedAt).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" })}</td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-dark-6">ไม่พบใบสมัคร</td></tr>}</tbody></table></div><div className="flex justify-between border-t border-stroke p-3 dark:border-stroke-dark"><p className="text-xs text-dark-6">แสดง {result?.items.length ?? 0} รายการ</p><div className="flex gap-2"><button disabled={page <= 1 || loading} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-stroke px-3 py-2 text-sm disabled:opacity-40">ก่อนหน้า</button><button disabled={page >= (result?.meta.totalPages ?? 1) || loading} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-stroke px-3 py-2 text-sm disabled:opacity-40">ถัดไป</button></div></div></section>
  </div>;
}
